version: "3"
services:
  consumer:
    build:
      context: ./state-consumer
      dockerfile: Dockerfile
    networks:
      - spark-streaming-network
    ports:
      - "4040:4040"
    env_file:
      - .env
networks:
  spark-streaming-network:
    external:
      name: spark-streaming-network